from logic import TruthTable
T = "Tautology"
print (T)
myTable = TruthTable(['p','q'], ['((p -> q) and p) -> q'])
myTable.display()
myTable.latex()
print (T)
myTable2 = TruthTable(['p','q'], ['(-q and (p -> q)) -> -p'])
myTable2.display()
myTable2.latex()
print (T)
myTable3 = TruthTable(['p','q','r'], ['((p -> q) and (q -> r)) -> (p -> r)'])
myTable3.display()
myTable3.latex()
print (T)
myTable4 = TruthTable(['p','q'], ['((p or q) and -p) -> q'])
myTable4.display()
myTable4.latex()
print (T)
myTable5 = TruthTable(['p','q'], ['p -> (p or q)'])
myTable5.display()
myTable5.latex()
print (T)
myTable6 = TruthTable(['p','q'], ['(p and q) -> p'])
myTable6.display()
myTable6.latex()
print (T)
myTable7 = TruthTable(['p','q'], ['((p) and (q)) -> (p and q)'])
myTable7.display()
myTable7.latex()
print (T)
myTable8 = TruthTable(['p','q','r'], ['((p or q) and (-p or r)) -> (q or r)'])
myTable8.display()
myTable8.latex()
